# Generated by Django 6.0.2 on 2026-02-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['user', '-created_at'], name='entry_entry_user_id_5deb98_idx'),
        ),
    ]
